//
//  AdItemVO.h
//  Generated by JSON Toolbox - http://itunes.apple.com/app/json-toolbox/id525015412
//
//  Created by hark on 3月 3, 2013
//

#import <Foundation/Foundation.h>


@interface AdItemVO : NSObject
{
} // End of Items

+ (NSArray*) ItemsWithArray: (NSArray*) array;
+ (AdItemVO *)ItemsWithDictionary: (NSDictionary *) dictionary;
+ (AdItemVO *)ItemsWithJSONString: (NSString *) jsonString usingEncoding: (NSStringEncoding) stringEncoding error: (NSError**) error;
- (id)initWithDictionary: (NSDictionary *) dictionary;
- (NSString*) description;

@property(nonatomic, retain) NSString * id;

@property(nonatomic, retain) NSString * shop_id;

@property(nonatomic, retain) NSString * date_group;

@property(nonatomic, retain) NSString * item_id;

@property(nonatomic, retain) NSString * num_iid;

@property(nonatomic, retain) NSString * taoke_status;

@property(nonatomic, retain) NSString * content_type;

@property(nonatomic, retain) NSString * pic_url;

@property(nonatomic, retain) NSString * price;

@property(nonatomic, retain) NSString * text;

@property(nonatomic, retain) NSString * short_url_key;

@property(nonatomic, retain) NSString * update_time;

@property(nonatomic, retain) NSString * status;


@end
