//
//  DetailVO.m
//  Generated by JSON Toolbox - http://itunes.apple.com/app/json-toolbox/id525015412
//
//  Created by hark on 3月 5, 2013
//

#import "DetailVO.h"

#if ! __has_feature(objc_arc)

	#define JSONAutoRelease(param) ([param autorelease]);

#else

	#define JSONAutoRelease(param) (param)

#endif

@implementation DetailVO

@synthesize lib_id, volume, is_fav, fav_count, num_iid, pic_url, message, price, short_url_key;

+ (NSArray*) DataWithArray: (NSArray*) array
{
    NSMutableArray * resultsArray = [[NSMutableArray alloc] init];

    for(id entry in array)
    {
        if(![entry isKindOfClass: [NSDictionary class]]) continue;

        [resultsArray addObject: [DetailVO DataWithDictionary: entry]];
    }

    return JSONAutoRelease(resultsArray);
} // End of DataWithArray

+ (DetailVO *)DataWithDictionary:(NSDictionary *)dictionary
{
    DetailVO *instance = [[DetailVO alloc] initWithDictionary: dictionary];
    return JSONAutoRelease(instance);
} // End of DataWithDictionary

+ (DetailVO *)DataWithJSONString: (NSString *) jsonString usingEncoding: (NSStringEncoding) stringEncoding error: (NSError**) error
{
    NSData * jsonData = [jsonString dataUsingEncoding: stringEncoding];

    NSDictionary * jsonDictionary = [NSJSONSerialization JSONObjectWithData: jsonData
                                                                    options: 0
                                                                      error: error];

    if(nil != error && nil != jsonDictionary)
    {
        return [DetailVO DataWithDictionary: jsonDictionary];
    }

    return nil;
} // End of DataWithJSONString

- (id)initWithDictionary:(NSDictionary *)dictionary
{
    self = [super init];
    if(self)
    {
        if(nil != [dictionary objectForKey: @"lib_id"])
            
        {
            
            self.lib_id = [dictionary objectForKey: @"lib_id"];
            
        }
        
        
        
        if(nil != [dictionary objectForKey: @"volume"])
            
        {
            
            self.volume = [dictionary objectForKey: @"volume"];
            
        }
        
        
        
        if(nil != [dictionary objectForKey: @"is_fav"])
            
        {
            
            self.is_fav = [dictionary objectForKey: @"is_fav"];
            
        }
        
        
        
        if(nil != [dictionary objectForKey: @"fav_count"])
            
        {
            
            self.fav_count = [dictionary objectForKey: @"fav_count"];
            
        }
        
        
        
        if(nil != [dictionary objectForKey: @"num_iid"])
            
        {
            
            self.num_iid = [dictionary objectForKey: @"num_iid"];
            
        }
        
        
        
        if(nil != [dictionary objectForKey: @"pic_url"])
            
        {
            
            self.pic_url = [dictionary objectForKey: @"pic_url"];
            
        }
        
        
        
        if(nil != [dictionary objectForKey: @"message"])
            
        {
            
            self.message = [dictionary objectForKey: @"message"];
            
        }
        
        
        
        if(nil != [dictionary objectForKey: @"price"])
            
        {
            
            self.price = [dictionary objectForKey: @"price"];
            
        }
        
        
        
        if(nil != [dictionary objectForKey: @"short_url_key"])
            
        {
            
            self.short_url_key = [dictionary objectForKey: @"short_url_key"];
            
        }
        
        
        
        
    }
    
    return self;
} // End of initWithDictionary

- (NSString*) description
{
    NSMutableString * descriptionOutput = [[NSMutableString alloc] init];
    [descriptionOutput appendFormat: @"lib_id = \"%@\"\r\n", lib_id];
    
    [descriptionOutput appendFormat: @"volume = \"%@\"\r\n", volume];
    
    [descriptionOutput appendFormat: @"is_fav = \"%@\"\r\n", is_fav];
    
    [descriptionOutput appendFormat: @"fav_count = \"%@\"\r\n", fav_count];
    
    [descriptionOutput appendFormat: @"num_iid = \"%@\"\r\n", num_iid];
    
    [descriptionOutput appendFormat: @"pic_url = \"%@\"\r\n", pic_url];
    
    [descriptionOutput appendFormat: @"message = \"%@\"\r\n", message];
    
    [descriptionOutput appendFormat: @"price = \"%@\"\r\n", price];
    
    [descriptionOutput appendFormat: @"short_url_key = \"%@\"\r\n", short_url_key];
    
    
    return JSONAutoRelease(descriptionOutput);
} // End of description

- (void)dealloc
{
#if ! __has_feature(objc_arc)
	[lib_id release];
    
	[volume release];
    
	[is_fav release];
    
	[fav_count release];
    
	[num_iid release];
    
	[pic_url release];
    
	[message release];
    
	[price release];
    
	[short_url_key release];
    
    
    [super dealloc];
#endif
} // End of dealloc

@end