//
//  GoodsVO.m
//  Generated by JSON Toolbox - http://itunes.apple.com/app/json-toolbox/id525015412
//
//  Created by hark on 3月 3, 2013
//

#import "GoodsVO.h"

#if ! __has_feature(objc_arc)
#define JSONAutoRelease(param) ([param autorelease]);
#else
#define JSONAutoRelease(param) (param)
#endif

@implementation GoodsVO

@synthesize id, shop_id, rect_rate, item_id, num_iid, weight, taoke_status, pic_url, price, content_type, short_url_key, update_time, status;

+ (NSArray*) ItemsWithArray: (NSArray*) array
{
    NSMutableArray * resultsArray = [[NSMutableArray alloc] init];

    for(id entry in array)
    {
        if(![entry isKindOfClass: [NSDictionary class]]) continue;
        
        GoodsVO * vo = [GoodsVO ItemsWithDictionary: entry];
        
        if (vo.pic_url && vo.rect_rate) {
            [resultsArray addObject: vo];
        }
    }

    return JSONAutoRelease(resultsArray);
} // End of ItemsWithArray

+ (GoodsVO *)ItemsWithDictionary:(NSDictionary *)dictionary
{
    GoodsVO *instance = [[GoodsVO alloc] initWithDictionary: dictionary];
    
    if (!instance.pic_url || !instance.rect_rate) {
        return nil;
    }
    
    return JSONAutoRelease(instance);
} // End of ItemsWithDictionary

+ (GoodsVO *)ItemsWithJSONString: (NSString *) jsonString usingEncoding: (NSStringEncoding) stringEncoding error: (NSError**) error
{
    NSData * jsonData = [jsonString dataUsingEncoding: stringEncoding];

    NSDictionary * jsonDictionary = [NSJSONSerialization JSONObjectWithData: jsonData
                                                                    options: 0
                                                                      error: error];

    if(nil != error && nil != jsonDictionary)
    {
        GoodsVO * vo = [GoodsVO ItemsWithDictionary: jsonDictionary];
        
        if (vo.pic_url && vo.rect_rate) {
            
            return vo;
        }
    }

    return nil;
} // End of ItemsWithJSONString

- (id)initWithDictionary:(NSDictionary *)dictionary
{
    self = [super init];
    if(self)
    {
        if(nil != [dictionary objectForKey: @"id"])

        {

            self.id = [dictionary objectForKey: @"id"];

        }



        if(nil != [dictionary objectForKey: @"shop_id"])

        {

            self.shop_id = [dictionary objectForKey: @"shop_id"];

        }



        if(nil != [dictionary objectForKey: @"rect_rate"] && ![[dictionary objectForKey: @"rect_rate"] isEqualToString:@""])

        {

            self.rect_rate = [dictionary objectForKey: @"rect_rate"];
            

        }
        
        if (!self.rect_rate || [self.rect_rate floatValue] == 0) {
            self.rect_rate = @"0.8";
        }



        if(nil != [dictionary objectForKey: @"item_id"])

        {

            self.item_id = [dictionary objectForKey: @"item_id"];

        }



        if(nil != [dictionary objectForKey: @"num_iid"])

        {

            self.num_iid = [dictionary objectForKey: @"num_iid"];

        }



        if(nil != [dictionary objectForKey: @"weight"])

        {

            self.weight = [dictionary objectForKey: @"weight"];

        }



        if(nil != [dictionary objectForKey: @"taoke_status"])

        {

            self.taoke_status = [dictionary objectForKey: @"taoke_status"];

        }



        if(nil != [dictionary objectForKey: @"pic_url"] && ![[dictionary objectForKey: @"pic_url"] isEqualToString:@""])

        {

            self.pic_url = [dictionary objectForKey: @"pic_url"];

        }



        if(nil != [dictionary objectForKey: @"price"])

        {

            self.price = [dictionary objectForKey: @"price"];

        }



        if(nil != [dictionary objectForKey: @"content_type"])

        {

            self.content_type = [dictionary objectForKey: @"content_type"];

        }



        if(nil != [dictionary objectForKey: @"short_url_key"])

        {

            self.short_url_key = [dictionary objectForKey: @"short_url_key"];

        }



        if(nil != [dictionary objectForKey: @"update_time"])

        {

            self.update_time = [dictionary objectForKey: @"update_time"];

        }



        if(nil != [dictionary objectForKey: @"status"])

        {

            self.status = [dictionary objectForKey: @"status"];

        }




    }

    return self;
} // End of initWithDictionary

- (NSString *)uuid
{
    return [NSString stringWithFormat:@"taodianhuo_%@_%@", self.item_id, self.short_url_key];
}

- (NSString*) description
{
    NSMutableString * descriptionOutput = [[NSMutableString alloc] init];
    [descriptionOutput appendFormat: @"id = \"%@\"\r\n", id];

    [descriptionOutput appendFormat: @"shop_id = \"%@\"\r\n", shop_id];

    [descriptionOutput appendFormat: @"rect_rate = \"%@\"\r\n", rect_rate];

    [descriptionOutput appendFormat: @"item_id = \"%@\"\r\n", item_id];

    [descriptionOutput appendFormat: @"num_iid = \"%@\"\r\n", num_iid];

    [descriptionOutput appendFormat: @"weight = \"%@\"\r\n", weight];

    [descriptionOutput appendFormat: @"taoke_status = \"%@\"\r\n", taoke_status];

    [descriptionOutput appendFormat: @"pic_url = \"%@\"\r\n", pic_url];

    [descriptionOutput appendFormat: @"price = \"%@\"\r\n", price];

    [descriptionOutput appendFormat: @"content_type = \"%@\"\r\n", content_type];

    [descriptionOutput appendFormat: @"short_url_key = \"%@\"\r\n", short_url_key];

    [descriptionOutput appendFormat: @"update_time = \"%@\"\r\n", update_time];

    [descriptionOutput appendFormat: @"status = \"%@\"\r\n", status];


    return JSONAutoRelease(descriptionOutput);
} // End of description

- (void)dealloc
{
#if ! __has_feature(objc_arc)
	[id release];

	[shop_id release];

	[rect_rate release];

	[item_id release];

	[num_iid release];

	[weight release];

	[taoke_status release];

	[pic_url release];

	[price release];

	[content_type release];

	[short_url_key release];

	[update_time release];

	[status release];


    [super dealloc];
#endif
} // End of dealloc

@end
